// <auto-generated />
namespace Dorm.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ct_Db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ct_Db));
        
        string IMigrationMetadata.Id
        {
            get { return "202106150054462_ct_Db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
